# This is a basic workflow to help you get started with Actions

name: luacheck

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: luacheck
        uses: nebularg/actions-luacheck@v1.1.0
        #with:
          #files: # optional, default is .
          #path: # optional, default is ${{ github.workspace }}
          #args: # optional
          #config: # optional
          #annotate: # optional, default is none
